import { Card, CardItem, CardItemAsset, CardState } from "../../src/1.domain/card/entities";
import { CardItemAssetStatusProps, CardItemTypeProps, StatusProps } from "../../src/1.domain/card/vo";


describe("domain 레이어에 card와 관련된 단위테스트", () => {
  const now = new Date();

  // 정합성에 사용할 card에 대한 레이어 테스트
  type TestCase1Props = {
    card_id: string | undefined;
    user_id: string | undefined;
    category_id: number | undefined;
    thumbnail_path: string | undefined;
    status: any;
    title: string | undefined;
    workspace_width: number | undefined;
    workspace_height: number | undefined;
    background_color: string | undefined;
    created_at?: Date | undefined;
    updated_at?: Date | undefined; 
    deleted_at?: Date | undefined;
    ok : boolean
  };

  const TestCase1 : Array<TestCase1Props> = [
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : undefined,
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },    
    {
      card_id : '     018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0    ',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '550e8400-e29b-41d4-a716-446655440000',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : undefined,
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '      018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0     ',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '550e8400-e29b-41d4-a716-446655440000',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 0,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : -1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : Array(2048).fill("a").join(""),
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : Array(2049).fill("a").join(""),
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "draft",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "published",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "another",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "  Archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : Array(255).fill("a").join(""),
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : Array(256).fill("a").join(""),
      workspace_height : 100,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 0,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : -1,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : undefined,
      workspace_width : 100,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 0,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : -1,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : undefined,
      background_color : "#ffcc00",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "rgb(255, 128, 0)",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "rgba(34, 12, 200, 0.5)",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : true
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : undefined,
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
    {
      card_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      user_id : '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      category_id : 1,
      thumbnail_path : "thumbnail.png",
      status : "archived",
      title : "나의 취미는",
      workspace_height : 100,
      workspace_width : 100,
      background_color : "basda",
      created_at : now,
      updated_at : now,
      deleted_at : now,
      ok : false
    },
  ];
  test.each(TestCase1)("card entity에 정합성 테스트", ({ card_id, user_id, category_id, thumbnail_path, status, title, workspace_height, workspace_width, background_color, created_at, updated_at, deleted_at, ok }) => {
    const test1 = () => {
      card_id = card_id as string;
      user_id = user_id as string;
      category_id = category_id as number;
      title = title as string;
      workspace_height = workspace_height as number;
      workspace_width = workspace_width as number;
      background_color = background_color as string;

      return new Card({ card_id, user_id, category_id, thumbnail_path, title, status, workspace_height, workspace_width, background_color, created_at, updated_at, deleted_at });
    };

    if ( ok ) {
      const t1 = test1();
      expect(t1.getCardId()).toBe(card_id?.trim());
      expect(t1.getUserId()).toBe(user_id?.trim());
      expect(t1.getCategoryId()).toBe(category_id);
      expect(t1.getThumbnailPath()).toBe(thumbnail_path?.trim());
      expect(t1.getTitle()).toBe(title?.trim());
      expect(t1.getStatus()).toBe(status?.trim().toLowerCase());
      expect(t1.getWorkSpaceWidth()).toBe(workspace_width);
      expect(t1.getWorkSpaceHeight()).toBe(workspace_height);
      expect(t1.getBackgroundColor()).toBe(background_color?.trim());
    } else {
      expect(test1).toThrow();
    }

  });


  // 정합성에 사용할 card에 레이어 테스트
  type TestCase2Props = {
      item_id: string | undefined;
      card_id: string | undefined;
      type: CardItemTypeProps | undefined;
      x: number | undefined;
      y: number | undefined;
      width: number | undefined;
      height: number | undefined;
      rotation: number | undefined;
      scale_x: number | undefined;
      scale_y: number | undefined;
      opacity: number | undefined;
      z_index: number | undefined;
      is_locked: boolean | undefined;
      is_visible: boolean | undefined;
      name: string | undefined;
      option: Record<string, any> | undefined;
      created_at: Date;
      updated_at: Date;
      deleted_at: Date | undefined;
      ok : boolean;
  };

  const TestCase2 : Array<TestCase2Props> = [
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: undefined,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '550e8400-e29b-41d4-a716-446655440000',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '      018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0     ',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: 'uuid',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: undefined,
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '       018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0     ',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '550e8400-e29b-41d4-a716-446655440000',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: "video",
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'image',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'Text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: '     text     ',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'another',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: undefined,
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 0,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: undefined,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 0,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: undefined,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 0,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: -1,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 0,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: undefined,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: undefined,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: -1,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: -1,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 0,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: -1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 0,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: -1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 0,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1.1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: -0.1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: -1,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: undefined,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: undefined,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: undefined,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: undefined,
      is_visible: true,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: undefined,
      name: 'title-text',
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: undefined,
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: Array(255).fill("n").join(""),
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: true,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: Array(256).fill("n").join(""),
      option: { text: 'hello', fontSize: 24 },
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    },
    {    
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      type: 'text',
      x: 10,
      y: 20,
      width: 200,
      height: 80,
      rotation: 0,
      scale_x: 1,
      scale_y: 1,
      opacity: 1,
      z_index: 0,
      is_locked: false,
      is_visible: true,
      name: 'title-text',
      option: undefined,
      created_at: now,
      updated_at: now,
      deleted_at: undefined,
      ok: false,
    }
  ]
  test.each(TestCase2)("card_item에 정합성 테스트", ({
    item_id, card_id, type, x, y, width, height, rotation, scale_x, scale_y, opacity, z_index, is_locked, is_visible, name, option, created_at, updated_at, deleted_at, ok
  }) => {
    const test2 = () => {
      item_id = item_id as string;
      card_id = card_id as string;
      type = type as string;
      x = x as number;
      y = y as number;
      width = width as number;
      height = height;
      rotation = rotation as number;
      scale_x = scale_x as number;
      scale_y = scale_y as number;
      opacity = opacity;
      z_index = z_index;
      is_locked = is_locked;
      is_visible = is_visible;
      name = name;
      option = option as Record<string, any>;
      created_at = created_at;
      updated_at = updated_at;
      deleted_at = deleted_at;
      return new CardItem({
        item_id, card_id, type, x, y, width, height, rotation, scale_x, scale_y, opacity, z_index, is_locked, is_visible, name, option, created_at, updated_at, deleted_at
      });
    };
    if (ok) {
      const t2 = test2();
      expect(t2.getItemId()).toBe(item_id?.trim());
      expect(t2.getCardId()).toBe(card_id?.trim());
      expect(t2.getType()).toBe(type?.trim().toLowerCase());
      expect(t2.getX()).toBe(x);
      expect(t2.getY()).toBe(y);
      expect(t2.getWidth()).toBe(width);
      expect(t2.getHeight()).toBe(height);
      expect(t2.getRotation()).toBe(rotation);
      expect(t2.getScaleX()).toBe(scale_x);
      expect(t2.getScaleY()).toBe(scale_y);
      expect(t2.getOpacity()).toBe(opacity);
      expect(t2.getZindex()).toBe(z_index);
      expect(t2.getIsLocked()).toBe(is_locked);
      expect(t2.getIsVisible()).toBe(is_visible);
      expect(t2.getName()).toBe(name?.trim());
      expect(t2.getOption()).toEqual(option);
    } else expect(test2).toThrow();
  });

  type TestCase3Props = {
    item_id: string | undefined;
    key_name: string | undefined;
    mime_type: string | undefined;
    size: number | undefined;
    status: any;
    created_at: Date | undefined;
    updated_at: Date | undefined;
    ok : boolean
  };    

  const TestCase3 : Array<TestCase3Props> = [
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: undefined,
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },    
    {
      item_id: '      018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0     ',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '550e8400-e29b-41d4-a716-446655440000',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "     test.png     ",
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : undefined,
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : Array(2048).fill("k").join(""),
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : Array(2049).fill("k").join(""),
      mime_type : "image/apng",
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : 'image/avif',
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : '    image/gif     ',
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : 'Image/aVif',
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : 'video/mp4',
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : 'video/mp',
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : undefined,
      size : 300,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 0,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : -1,
      status : "failed",
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "ready",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "uploading",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : undefined,
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "     failed     ",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "FaileD",
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      item_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      key_name : "test.png",
      mime_type : "image/apng",
      size : 300,
      status : "another",
      created_at : now,
      updated_at : now,
      ok : false
    }
  ];

  test.each(TestCase3)("card_item asset에 정합성 테스트", ({ item_id, key_name, mime_type, size, status, created_at, updated_at, ok }) => {
    const test3 = () => {
      item_id = item_id as string;
      key_name = key_name as string;
      mime_type = mime_type as string;
      size = size as number;
      return new CardItemAsset({
        item_id, key_name, mime_type, size, status, created_at, updated_at
      });
    };
    if ( ok ) {
      const t3 = test3();
      expect(t3.getItemId()).toBe(item_id?.trim());
      expect(t3.getKeyName()).toBe(key_name?.trim());
      expect(t3.getMimeType()).toBe(mime_type?.trim().toLowerCase());
      expect(t3.getStatus()).toBe(status?.trim().toLowerCase());
      expect(t3.getSize()).toBe(size);
    }else {
      expect(test3).toThrow();
    }
  });

  type TestCase4Props = {
    id: number | undefined;
    card_id: string | undefined;
    like_count: number | undefined;
    view_count: number | undefined;
    created_at: Date;
    updated_at: Date;
    ok : boolean
  };

  const TestCase4 : Array<TestCase4Props> = [
    {
      id: 1,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: 0,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      id: 0,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: 0,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      id: -1,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: 0,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      id: 1,
      card_id: undefined,
      like_count: 0,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      id: 1,
      card_id: '550e8400-e29b-41d4-a716-446655440000',
      like_count: 0,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      id: 1,
      card_id: '    018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0      ',
      like_count: 0,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      id: 1,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: 1,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      id: 1,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: -1,
      view_count: 0,
      created_at : now,
      updated_at : now,
      ok : false
    },
    {
      id: 1,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: 0,
      view_count: 1,
      created_at : now,
      updated_at : now,
      ok : true
    },
    {
      id: 1,
      card_id: '018e9a48-3c8a-7b20-bc9d-9f5b8e9f88c0',
      like_count: 0,
      view_count: -1,
      created_at : now,
      updated_at : now,
      ok : false
    },
  ];

  test.each(TestCase4)("card_stat의 정합성 테스트", ({ id, card_id, like_count, view_count, created_at, updated_at, ok }) => {
    const test4 = () => {
      id = id as number;
      card_id = card_id as string;
      like_count = like_count as number;
      view_count = view_count as number;
      return new CardState({
        id, card_id, like_count, view_count, created_at, updated_at
      });
    }

    if ( ok ) {
      const t4 = test4();
      expect(t4.getId()).toBe(id);
      expect(t4.getCardId()).toBe(card_id?.trim());
      expect(t4.getLikeCount()).toBe(like_count);
      expect(t4.getViewCount()).toBe(view_count);
    } else expect(test4).toThrow();

  });

});